In [2]:
import pandas as pd

In [17]:
# Filtering DataFrames
df = pd.read_csv("summer.csv")
df

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [14]:
#basic filtering syntax
df["Country"] == "SWE"

0        False
1        False
2        False
3        False
4        False
         ...
31160    False
31161    False
31162    False
31163    False
31164     True
Name: Country, Length: 31165, dtype: bool

In [ ]:
(df["Country"] == "SWE").value_counts()

Country
False    30121
True      1044
Name: count, dtype: int64

In [20]:
swe = df["Country"] == "SWE"
fra = df["Country"] == "FRA"

In [21]:
df.loc[swe | fra]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
17,1896,Athens,Athletics,Athletics,"LERMUSIAUX, Albin",FRA,Men,1500M,Bronze
47,1896,Athens,Athletics,Athletics,"TUFFERI, Alexandre",FRA,Men,Triple Jump,Silver
51,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,100KM,Gold
54,1896,Athens,Cycling,Cycling Track,"MASSON, Paul",FRA,Men,10KM,Gold
55,1896,Athens,Cycling,Cycling Track,"FLAMENG, Léon",FRA,Men,10KM,Silver
...,...,...,...,...,...,...,...,...,...
30939,2012,London,Tennis,Tennis,"GASQUET, Richard",FRA,Men,Doubles,Bronze
30962,2012,London,Triathlon,Triathlon,"NORDEN, Lisa",SWE,Women,Individual,Silver
31139,2012,London,Wrestling,Wrestling Freestyle,"EUREN, Johan",SWE,Men,Wg 120 KG,Bronze
31151,2012,London,Wrestling,Wrestling Freestyle,"GUENOT, Steeve",FRA,Men,Wg 66 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

# comparison operators / evaluation methods

When filtering you can use any operation/expression/method that evaluates to True/False.

We will look at the following commonly used expressions/methods when filtering:


- `==`
- `<`
- `between()`
- `isin()`

In [22]:
df.loc[df.Year < 2000]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
23156,1996,Atlanta,Wrestling,Wrestling Gre-R,"OLEYNYK, Vyacheslav",UKR,Men,82 - 90KG (Light-Heavyweight),Gold
23157,1996,Atlanta,Wrestling,Wrestling Gre-R,"FAFINSKI, Jacek",POL,Men,82 - 90KG (Light-Heavyweight),Silver
23158,1996,Atlanta,Wrestling,Wrestling Gre-R,"LJUNGBERG, Mikael",SWE,Men,90 - 100KG (Heavyweight),Bronze
23159,1996,Atlanta,Wrestling,Wrestling Gre-R,"WRONSKI, Andrzej",POL,Men,90 - 100KG (Heavyweight),Gold
23160,1996,Atlanta,Wrestling,Wrestling Gre-R,"LISHTVAN, Sergey",BLR,Men,90 - 100KG (Heavyweight),Silver

In [ ]:
df.loc[df["City"].isin(["London","Year"])]

In [ ]:
df.loc[df["Year"].between(1992,2000)]

In [25]:
#We must use parethesis whe using multiple conditions
df.loc[(df.Country == "SWE") & (df.Gender == "Women")]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
1875,1908,London,Tennis,Tennis,"ADLERSTRAHLE, Märtha",SWE,Women,Singles Indoor,Bronze
1941,1912,Stockholm,Aquatics,Diving,"JOHANSSON, Greta",SWE,Women,10M Platform,Gold
1942,1912,Stockholm,Aquatics,Diving,"REGNELL, Lisa",SWE,Women,10M Platform,Silver
2772,1912,Stockholm,Tennis,Tennis,"FICK, Sigrid",SWE,Women,Mixed Doubles,Silver
2776,1912,Stockholm,Tennis,Tennis,"FICK, Sigrid",SWE,Women,Mixed Doubles Indoor,Bronze
...,...,...,...,...,...,...,...,...,...
26784,2004,Athens,Sailing,Sailing,"TORGERSSON, Therese",SWE,Women,470 - Two Person Dinghy,Bronze
26785,2004,Athens,Sailing,Sailing,"ZACHRISSON, Vendela",SWE,Women,470 - Two Person Dinghy,Bronze
28028,2008,Beijing,Cycling,Cycling Road,"JOHANSSON, Emma",SWE,Women,Individual Road Race,Silver
30094,2012,London,Equestrian,Eventing,"ALGOTSSON, Sara",SWE,Women,Individual,Silver
30962,2012,London,Triathlon,Triathlon,"NORDEN, Lisa",SWE,Women,Individual,Silver

In [26]:
female = df.Gender == "Women"

In [27]:
df.loc[swe & female]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
1875,1908,London,Tennis,Tennis,"ADLERSTRAHLE, Märtha",SWE,Women,Singles Indoor,Bronze
1941,1912,Stockholm,Aquatics,Diving,"JOHANSSON, Greta",SWE,Women,10M Platform,Gold
1942,1912,Stockholm,Aquatics,Diving,"REGNELL, Lisa",SWE,Women,10M Platform,Silver
2772,1912,Stockholm,Tennis,Tennis,"FICK, Sigrid",SWE,Women,Mixed Doubles,Silver
2776,1912,Stockholm,Tennis,Tennis,"FICK, Sigrid",SWE,Women,Mixed Doubles Indoor,Bronze
...,...,...,...,...,...,...,...,...,...
26784,2004,Athens,Sailing,Sailing,"TORGERSSON, Therese",SWE,Women,470 - Two Person Dinghy,Bronze
26785,2004,Athens,Sailing,Sailing,"ZACHRISSON, Vendela",SWE,Women,470 - Two Person Dinghy,Bronze
28028,2008,Beijing,Cycling,Cycling Road,"JOHANSSON, Emma",SWE,Women,Individual Road Race,Silver
30094,2012,London,Equestrian,Eventing,"ALGOTSSON, Sara",SWE,Women,Individual,Silver
30962,2012,London,Triathlon,Triathlon,"NORDEN, Lisa",SWE,Women,Individual,Silver

In [30]:
df["Country"].unique()

<StringArray>
['HUN', 'AUT', 'GRE', 'USA', 'GER', 'GBR', 'FRA', 'AUS', 'DEN', 'SUI',
 ...
   nan, 'BRN', 'GUA', 'GRN', 'TTO', 'BOT', 'MNE', 'CYP', 'SGP', 'GAB']
Length: 148, dtype: str

In [31]:
df.loc[~(df["Gender"] == "Men") & df["Country"].isin(["SWE","NOR","DEN"])]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
1875,1908,London,Tennis,Tennis,"ADLERSTRAHLE, Märtha",SWE,Women,Singles Indoor,Bronze
1941,1912,Stockholm,Aquatics,Diving,"JOHANSSON, Greta",SWE,Women,10M Platform,Gold
1942,1912,Stockholm,Aquatics,Diving,"REGNELL, Lisa",SWE,Women,10M Platform,Silver
2772,1912,Stockholm,Tennis,Tennis,"FICK, Sigrid",SWE,Women,Mixed Doubles,Silver
2776,1912,Stockholm,Tennis,Tennis,"FICK, Sigrid",SWE,Women,Mixed Doubles Indoor,Bronze
...,...,...,...,...,...,...,...,...,...
30451,2012,London,Handball,Handball,"RIEGELHUTH, Linn-Kristin",NOR,Women,Handball,Gold
30452,2012,London,Handball,Handball,"SNORROEGGEN, Goeril",NOR,Women,Handball,Gold
30453,2012,London,Handball,Handball,"SULLAND, Linn Jorum",NOR,Women,Handball,Gold
30783,2012,London,Rowing,Rowing,"ERICHSEN, Fie Udby",DEN,Women,Single Sculls,Silver
30962,2012,London,Triathlon,Triathlon,"NORDEN, Lisa",SWE,Women,Individual,Silver

# Challenge

1. How many olympic medals did the swedish shooter "SWAHN, Alfred" win?
2. How many medals in total have Sweden won in the three disciplines Swimming, Athletics & Rowing?
3. How many medals did Greece win in the 1896 OS, excluding medals won in the Swimming discipline?

In [ ]:
df.loc[(df["Athlete"]== "SWAHN, Alfred")].Medal.value_counts

Medal
Gold      3
Silver    3
Bronze    3
Name: count, dtype: int64

In [ ]:
df.loc[(df["Country"]== "SWE") & (df["Discipline"].isin(["Swimming","Athletics","Rowing"]))][["Discipline","Medal"]].value_counts().unstack()

Medal       Bronze  Gold  Silver
Discipline
Athletics     51.0  21.0    31.0
Swimming      33.0   8.0    23.0
Rowing         NaN   NaN    10.0

In [50]:
df.loc[((df["Country"]== "GRE") & (df["Year"]== 1896) & ~(df["Discipline"]== "Swimming"))]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
23,1896,Athens,Athletics,Athletics,"GOLEMIS, Dimitrios",GRE,Men,800M,Bronze
26,1896,Athens,Athletics,Athletics,"VERSIS, Sotirios",GRE,Men,Discus Throw,Bronze
28,1896,Athens,Athletics,Athletics,"PARASKEVOPOULOS, Panagiotis",GRE,Men,Discus Throw,Silver
36,1896,Athens,Athletics,Athletics,"LOUIS, Spyridon",GRE,Men,Marathon,Gold
37,1896,Athens,Athletics,Athletics,"VASILAKOS, Kharilaos",GRE,Men,Marathon,Silver
38,1896,Athens,Athletics,Athletics,"DAMASKOS, Evangelos",GRE,Men,Pole Vault,Bronze
39,1896,Athens,Athletics,Athletics,"THEODOROPOULOS, Ioannis",GRE,Men,Pole Vault,Bronze
42,1896,Athens,Athletics,Athletics,"PAPASIDERIS, Georgios",GRE,Men,Shot Put,Bronze
44,1896,Athens,Athletics,Athletics,"GOUSKOS, Miltiadis",GRE,Men,Shot Put,Silver
45,1896,Athens,Athletics,Athletics,"PERSAKIS, Ioannis",GRE,Men,Triple Jump,Bronze
49,1896,Athens,Cycling,Cycling Road,"KONSTANTINIDIS, Aristidis",GRE,Men,Individual Road Race,Gold
52,1896,Athens,Cycling,Cycling Track,"KOLETTIS, Georgios",GRE,Men,100KM,Silver
60,1896,Athens,Cycling,Cycling Track,"NIKOLOPOULOS, Stamatios",GRE,Men,1KM Time Trial,Silver
63,1896,Athens,Cycling,Cycling Track,"NIKOLOPOULOS, Stamatios",GRE,Men,Sprint Indivual,Silver
64,1896,Athens,Fencing,Fencing,"PIERRAKOS-MAVROMICHALIS, Perikles",GRE,Men,Foil Individual,Bronze
67,1896,Athens,Fencing,Fencing,"PYRGOS, Leonidas",GRE,Men,"Foil, Masters",Gold
70,1896,Athens,Fencing,Fencing,"GEORGIADIS, Ioannis",GRE,Men,Sabre Individual,Gold
71,1896,Athens,Fencing,Fencing,"KARAKALOS, Telemachos",GRE,Men,Sabre Individual,Silver
78,1896,Athens,Gymnastics,Artistic G.,"PERSAKIS, Petros",GRE,Men,Rings,Bronze
79,1896,Athens,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,Rings,Gold
82,1896,Athens,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,Rope Climbing,Gold
83,1896,Athens,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,Rope Climbing,Silver
95,1896,Athens,Gymnastics,Artistic G.,"CHRYSAPHIS, Ioannis",GRE,Men,"Team, Parallel Bars",Bronze
96,1896,Athens,Gymnastics,Artistic G.,"KARVELAS, Phillippos",GRE,Men,"Team, Parallel Bars",Bronze
97,1896,Athens,Gymnastics,Artistic G.,"LOUNDRAS, Dimitrios",GRE,Men,"Team, Parallel Bars",Bronze
98,1896,Athens,Gymnastics,Artistic G.,"MITROPOULOS, Ioannis",GRE,Men,"Team, Parallel Bars",Bronze
110,1896,Athens,Gymnastics,Artistic G.,"ANDRIAKOPOULOS, Nicolaos",GRE,Men,"Team, Parallel Bars",Silver
111,1896,Athens,Gymnastics,Artistic G.,"ATHANASOPOULOS, Spyros",GRE,Men,"Team, Parallel Bars",Silver
112,1896,Athens,Gymnastics,Artistic G.,"PERSAKIS, Petros",GRE,Men,"Team, Parallel Bars",Silver
113,1896,Athens,Gymnastics,Artistic G.,"XENAKIS, Thomasios",GRE,Men,"Team, Parallel Bars",Silver
117,1896,Athens,Shooting,Shooting,"MORAKIS, Nikolaos",GRE,Men,25M Army Pistol,Bronze
121,1896,Athens,Shooting,Shooting,"PHRANGOUDIS, Joannis",GRE,Men,25M Rapid Fire Pistol (60 Shots),Gold
122,1896,Athens,Shooting,Shooting,"ORPHANIDIS, Georgios",GRE,Men,25M Rapid Fire Pistol (60 Shots),Silver
123,1896,Athens,Shooting,Shooting,"PHRANGOUDIS, Joannis",GRE,Men,50M Pistol (60 Shots),Bronze
126,1896,Athens,Shooting,Shooting,"TRIKUPIS, Nicolaos",GRE,Men,"Army Rifle, 200M",Bronze
127,1896,Athens,Shooting,Shooting,"KARASEVDAS, Pantelis",GRE,Men,"Army Rifle, 200M",Gold
128,1896,Athens,Shooting,Shooting,"PAVLIDIS, Pavlos",GRE,Men,"Army Rifle, 200M",Silver
130,1896,Athens,Shooting,Shooting,"ORPHANIDIS, Georgios",GRE,Men,"Army Rifle, 300M",Gold
131,1896,Athens,Shooting,Shooting,"PHRANGOUDIS, Joannis",GRE,Men,"Army Rifle, 300M",Silver
138,1896,Athens,Tennis,Tennis,"PASPATIS, Konstantinos",GRE,Men,Singles,Bronze
141,1896,Athens,Tennis,Tennis,"KASDAGLIS, Dionysios",GRE,Men,Singles,Silver
142,1896,Athens,Weightlifting,Weightlifting,"NIKOLOPOULOS, Alexandros",GRE,Men,Heavyweight - One Hand Lift,Bronze
145,1896,Athens,Weightlifting,Weightlifting,"VERSIS, Sotirios",GRE,Men,Heavyweight - Two Hand Lift,Bronze
148,1896,Athens,Wrestling,Wrestling Gre-R,"CHRISTOPOULOS, Stephanos",GRE,Men,Open Event,Bronze
150,1896,Athens,Wrestling,Wrestling Gre-R,"TSITAS, Georgios",GRE,Men,Open Event,Silver