## LIST COMPREHENSIONS
List comprehensions is a way of combining storage and iteration streamlined logic!

In [3]:
numbers = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [4]:
squared = []

for i in numbers:
    squared.append(i ** 2)

squared

[1, 16, 81, 256, 625, 1296, 2401, 4096, 6561, 10000]

In [6]:
squared2 = [i ** 2 for i in numbers]
squared2

[1, 16, 81, 256, 625, 1296, 2401, 4096, 6561, 10000]

## list comprehensions with if statments

In [7]:
product_ids = [12101, 12202, 12303, 12404, 12505, 12606, 12707, 12808, 12209, 12312, 12312, 12298, 12234]

In [11]:
# we want to find product ids starting with 122
filtred = [i for i in product_ids if str(i).startswith("122")]
filtred

[12202, 12209, 12298, 12234]

In [ ]:
#TERNARY OPERATORS

order_amount = 150
is_premium_member = True

discount_percentage = 10 if is_premium_member else 5
final_price = order_amount - (order_amount * discount_percentage / 100)


print(f"Final Price: ${final_price:.2f}")

In [ ]:
#TERNARY OPERATOR INSIDE LIST COMPREHENSION

exam_grades = [91, 86, 94, 63, 97, 73, 90, 79, 45, 57, 60, 54, 76, 93, 69, 43, 56, 89, 66, 78, 46, 47, 97, 61, 52]

passing_threshold = 70

grade_status = [("Pass",i) if passing_threshold < i else ("Fail",i) for i in exam_grades]

grade_status

#NESTED LIST COMPREENHSIONS - TWO APROACHES

In [ ]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

squared_matrix =[[number ** 2 for number in row] for row in matrix]

squared_matrix


## BIG BRAIN SHIIIIIT YOOOOOOO
## STUDY THIS SNALLLAAAAA

# In this syntax, the outer loop iterates through each `row` in the matrix, and the inner loop 
# iterates through each `num` in the current `row`. This results in creating a new matrix where 
# each element is the square of the corresponding element in the original matrix.

[[1, 4, 9], [16, 25, 36], [49, 64, 81]]

In [ ]:
[num ** 2 for row in matrix for num in row] # with this aproach its a sigle list

[1, 4, 9, 16, 25, 36, 49, 64, 81]

## List comp with long if statments

In [22]:
applicants = [
    {'name': 'Alice', 'primary_coding_language': ["Python"], 'skills': ['Python', 'JavaScript', 'HTML', 'CSS']},
    {'name': 'Bob', 'primary_coding_language': ["Java"], 'skills': ['Java', 'Python', 'SQL']},
    {'name': 'Carol', 'primary_coding_language': ["Python"], 'skills': ['Python', 'Ruby', 'React']},
    {'name': 'David', 'primary_coding_language': ["Python"], 'skills': ['Python', 'Django', 'Angular']},
    {'name': 'Jean', 'primary_coding_language': ["Python"], 'skills': ['Python', 'JavaScript', 'HTML', 'CSS']},
    {'name': 'Claude', 'primary_coding_language': ["Python"], 'skills': ['Java', 'C++', 'SQL']},
    {'name': 'Finn', 'primary_coding_language': ["C#"], 'skills': ['C#', 'Ruby', 'React']},
    {'name': 'Achill', 'primary_coding_language': ["Python"], 'skills': ['Python', 'Django', 'Angular']}
]

In [ ]:
# we want to find a guy that has python as primary language and HTML and CSS skills 

[i["name"] for i in applicants if i["primary_coding_language"][0] \
 == "Python" and all(j in i["skills"] for j in ["HTML","CSS"])]

['Alice', 'Jean']

In [32]:
[i["name"] for i in applicants if i["primary_coding_language"][0] \
 == "Python" and any(j in i["skills"] for j in ["HTML","CSS"])]

['Alice', 'Jean']

## Practical Uses for List Comprehensions

#### Reading Multiple Files
One use case where list comprehensions come in handy is when data is split across multiple files. For example, suppose we had a data directory that contained several CSV files (among other files), each with the same information (columns) for separate groups or divisions. We could use a list comprehension with an endswith('.csv') condition in it to get a list of just the CSV files in that directory. We could use another list comprehension to have Pandas read each of those files and then the pd.concat method to combine them all into a single data set that we can analyze as follows.

In [44]:
import pandas as pd
import os
os.getcwd()

'/Users/hugocarvalho/Documents/nod_coding_bootcamp/codealongs/week_1'

In [36]:
path = os.path.join(os.getcwd(), "data")

path

'/Users/hugocarvalho/Documents/nod_coding_bootcamp/codealongs/week_1/data'

In [37]:
os.getcwd()

'/Users/hugocarvalho/Documents/nod_coding_bootcamp/codealongs/week_1'

In [40]:
os.listdir(path)

['vehicles_tab.txt',
 'boys2020.csv',
 'boys2018.csv',
 'boys2019.csv',
 'boys2016.csv',
 'vehicles.xlsx',
 'vehicles.csv']

In [41]:
[file for file in os.listdir(path) if ".xlsx" in file]

['vehicles.xlsx']

In [46]:
## READING MULTIPLE FILES WITH LIST COMPRENSION
lst_files = [file for file in os.listdir(path) if file.startswith("boy") and file.endswith(".csv")]

In [48]:
read_files = [pd.read_csv(os.path.join(path, file)) for file in lst_files]
read_files

[          Name  Count  Rank
 0         Adam    602    10
 1       Adrian    424    30
 2        Albin    320    47
 3    Alexander    521    17
 4       Alfred    555    13
 ..         ...    ...   ...
 96      Vilgot    192    75
 97     Wilhelm    182    77
 98     William    742     2
 99      Wilmer    188    76
 100    Vincent    501    18

 [101 rows x 3 columns],
           Name  Count  Rank
 0         Adam    647     9
 1       Adrian    442    28
 2       Albin     321    46
 3   Alexander     626    10
 4       Alfred    502    15
 ..         ...    ...   ...
 95     Wilhelm    231    68
 96       Ville    167    88
 97    William     863     1
 98     Wilmer     247    64
 99     Vincent    501    16

 [100 rows x 3 columns],
           Name  Count  Rank
 0         Adam    620     9
 1       Adrian    503    17
 2       Albin     347    41
 3   Alexander     563    12
 4       Alfred    510    15
 ..         ...    ...   ...
 95     Wilhelm    220    70
 96       Ville    150    91
 97     William    732     3
 98     Wilmer     249    63
 99     Vincent    476    22

 [100 rows x 3 columns],
           Name  Count  Rank
 0         Adam    579    11
 1       Adrian    556    14
 2       Albin     374    38
 3   Alexander     668     7
 4      Alfred     541    17
 ..         ...    ...   ...
 95     Wilhelm    228    73
 96       Ville    234    71
 97     William    850     3
 98     Wilmer     289    54
 99     Vincent    537    19

 [100 rows x 3 columns]]

In [52]:
##DF IS CONVENTION FOR DATA FRAME
df = pd.concat(read_files, axis=0)
df

         Name  Count  Rank
0        Adam    602    10
1      Adrian    424    30
2       Albin    320    47
3   Alexander    521    17
4      Alfred    555    13
..        ...    ...   ...
95    Wilhelm    228    73
96      Ville    234    71
97    William    850     3
98    Wilmer     289    54
99    Vincent    537    19

[401 rows x 3 columns]

In [53]:
df = pd.read_csv(os.path.join(path,"vehicles.csv"))
df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [54]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='str')

In [63]:
selected_cols = [col for col in df._get_numeric_data()]
df[selected_cols]

,Year,Engine Displacement,Cylinders,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,1984,2.5,4.0,19.388824,18,17,17,522.764706,1950
1,1984,4.2,6.0,25.354615,13,13,13,683.615385,2550
2,1985,2.5,4.0,20.600625,16,17,16,555.437500,2100
3,1985,4.2,6.0,25.354615,13,13,13,683.615385,2550
4,1987,3.8,6.0,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...
35947,2013,1.0,3.0,9.155833,34,38,36,244.000000,1100
35948,2014,1.0,3.0,9.155833,34,38,36,243.000000,1100
35949,2015,1.0,3.0,9.155833,34,38,36,244.000000,1100
35950,2016,0.9,3.0,9.155833,34,39,36,246.000000,1100
35951,2016,0.9,3.0,9.417429,32,39,35,255.000000,1150

In [61]:
selected_cols = [col for col in df._get_numeric_data() if df[col].mean() > 15]

df[selected_cols]

,Year,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,1984,19.388824,18,17,17,522.764706,1950
1,1984,25.354615,13,13,13,683.615385,2550
2,1985,20.600625,16,17,16,555.437500,2100
3,1985,25.354615,13,13,13,683.615385,2550
4,1987,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...
35947,2013,9.155833,34,38,36,244.000000,1100
35948,2014,9.155833,34,38,36,243.000000,1100
35949,2015,9.155833,34,38,36,244.000000,1100
35950,2016,9.155833,34,39,36,246.000000,1100
35951,2016,9.417429,32,39,35,255.000000,1150

## DICTIONARY COMPRENSION

In [65]:
names = ["Hugo", "Gabi", "Lisa", "Axel", "Lovisa"]

names_length = {name : len(name) for name in names}

names_length

{'Hugo': 4, 'Gabi': 4, 'Lisa': 4, 'Axel': 4, 'Lovisa': 6}