<img src="https://iili.io/2FquTQ4.png" alt="2FquTQ4.png" border="0" width="150" />

#  List Comprehensions | Challenge 2

### Intro
This lab focuses on constructing list comprehensions to extract and filter information in different ways.

Read the instructions carefully. If you get stuck it is OK to move on to the next question.


### Resources

- [List Comprehensions | Python Documentation](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)
- [Using List Comprehensions With Pandas](https://chrisalbon.com/python/data_wrangling/pandas_list_comprehension/)

In [1]:
#import these libraries
import os
import numpy as np
import pandas as pd

# Q1

## Q1.1 

Use the `getcwd()` method from the `os` library to find out which directory you are in

In [2]:
os.getcwd()

'/Users/hugocarvalho/Documents/nod_coding_bootcamp/lab/week_1/day_4'

## Q1.2
Change to your "/data" directory

In [17]:
path = "/Users/hugocarvalho/Documents/nod_coding_bootcamp/lab/week_1/day_4"

os.chdir(os.path.join(path,"data"))

data_path = os.getcwd()

## Q1.3
Create a list with the files in your directory

In [14]:
dir_list = os.listdir()
dir_list

['random_data6.xlsx',
 'random_data7.xlsx',
 'random_data10.csv',
 'random_data6.csv',
 'random_data7.csv',
 'random_data5.csv',
 'random_data4.csv',
 'random_data1.xlsx',
 'random_data1.csv',
 'random_data3.csv',
 'random_data2.csv',
 'random_data2.xlsx',
 'random_data9.csv',
 'random_data10.xlsx',
 'random_data8.csv',
 'random_data3.xlsx',
 'random_data4.xlsx',
 'random_data8.xlsx',
 'random_data9.xlsx',
 'random_data5.xlsx']

## Q1.4

Now create a list named `file_list` with only the csv-files in your data directory using a list comprehension

In [8]:
file_list = [i for i in dir_list if i.endswith(".csv")]
file_list

['random_data10.csv',
 'random_data6.csv',
 'random_data7.csv',
 'random_data5.csv',
 'random_data4.csv',
 'random_data1.csv',
 'random_data3.csv',
 'random_data2.csv',
 'random_data9.csv',
 'random_data8.csv']

# Q2 - Pandas

### Intro
You will use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single dataframe. 


We will then examine the dataframe and look into the indexing

## Q2.1

Make sure that you are in the data directory (containing the files)

In [18]:
all_files_list = [pd.read_csv(os.path.join(data_path,file_name)) for file_name in file_list]
all_files_list

[          0         1         2         3         4         5         6  \
 0  0.972077  0.646035  0.533126  0.943473  0.023868  0.955283  0.165667
 1  0.819736  0.758109  0.794889  0.309026  0.580838  0.674574  0.431448
 2  0.075542  0.893006  0.705055  0.881107  0.127228  0.396477  0.986381
 3  0.170463  0.480887  0.258983  0.072511  0.816111  0.474031  0.745129
 4  0.415139  0.889190  0.263780  0.258482  0.554022  0.388369  0.007417
 5  0.147106  0.074295  0.045481  0.834139  0.600065  0.095220  0.802513

           7         8         9
 0  0.715487  0.269452  0.736947
 1  0.349162  0.109140  0.987664
 2  0.897388  0.762901  0.210352
 3  0.148653  0.890304  0.520209
 4  0.194194  0.576059  0.956678
 5  0.950219  0.933484  0.106030  ,
           0         1         2         3         4         5         6  \
 0  0.264027  0.964930  0.166019  0.979061  0.923937  0.623234  0.834406
 1  0.258320  0.637756  0.317591  0.192193  0.220216  0.449298  0.121003
 2  0.340470  0.946588  0.604095  0.913370  0.193863  0.435900  0.636458
 3  0.568930  0.009381  0.598609  0.223873  0.303780  0.349022  0.348644
 4  0.325928  0.580347  0.808592  0.616384  0.602156  0.102621  0.390492
 5  0.943521  0.206190  0.051978  0.852592  0.160536  0.573881  0.142216

           7         8         9
 0  0.930507  0.839160  0.522875
 1  0.853171  0.658405  0.582496
 2  0.579789  0.644397  0.779777
 3  0.259113  0.219026  0.524392
 4  0.606321  0.022965  0.624083
 5  0.584250  0.364259  0.248642  ,
           0         1         2         3         4         5         6  \
 0  0.707485  0.789624  0.425679  0.117072  0.154292  0.181508  0.156848
 1  0.009849  0.230776  0.833235  0.570922  0.195540  0.810397  0.951304
 2  0.437908  0.445475  0.387031  0.723512  0.542042  0.824992  0.902477
 3  0.355867  0.021528  0.197228  0.015251  0.688148  0.247983  0.371156
 4  0.699331  0.558848  0.874878  0.565221  0.227320  0.523653  0.386730
 5  0.446181  0.897401  0.307030  0.375517  0.132631  0.662397  0.999179

           7         8         9
 0  0.647157  0.236120  0.873562
 1  0.642084  0.860988  0.485705
 2  0.137933  0.336383  0.546531
 3  0.511989  0.697104  0.717978
 4  0.920449  0.209092  0.210046
 5  0.593294  0.968715  0.955091  ,
           0         1         2         3         4         5         6  \
 0  0.740576  0.703888  0.635960  0.201376  0.333506  0.921203  0.240422
 1  0.955814  0.180323  0.922775  0.061503  0.252939  0.494738  0.737009
 2  0.139840  0.478558  0.349587  0.173535  0.605319  0.149547  0.224081
 3  0.223433  0.358509  0.617079  0.882206  0.243871  0.422363  0.337593
 4  0.529934  0.720701  0.613672  0.475738  0.838735  0.667907  0.039340
 5  0.551652  0.778406  0.115201  0.253204  0.241417  0.638059  0.631762

           7         8         9
 0  0.507092  0.710404  0.496614
 1  0.582887  0.214657  0.570323
 2  0.017461  0.256106  0.031711
 3  0.758400  0.729243  0.014322
 4  0.806723  0.803851  0.457624
 5  0.059920  0.122759  0.981465  ,
           0         1         2         3         4         5         6  \
 0  0.385390  0.749017  0.251410  0.006835  0.317852  0.595623  0.386616
 1  0.113076  0.622563  0.550221  0.105007  0.410163  0.050102  0.975362
 2  0.440056  0.730651  0.367334  0.097116  0.833843  0.124944  0.500654
 3  0.629227  0.641817  0.863553  0.015075  0.907014  0.988228  0.241888
 4  0.574716  0.024898  0.120578  0.856961  0.201969  0.002041  0.867184
 5  0.596758  0.205773  0.312754  0.344289  0.916072  0.462229  0.870788

           7         8         9
 0  0.264623  0.164532  0.850798
 1  0.123897  0.096226  0.267682
 2  0.486800  0.875116  0.710462
 3  0.633092  0.487083  0.847807
 4  0.539172  0.890132  0.757211
 5  0.433023  0.963572  0.951630  ,
           0         1         2         3         4         5         6  \
 0  0.584671  0.554514  0.803746  0.080318  0.195672  0.571731  0.434800
 1  0.163314  0.540963  0.747248  0.412400  0.392086  0.895591  0.302680
 2  0.897660  0.608840  0.981982  0.983594  0.768925  0.170911  0.189931
 3  0.509013  0.782233  0.111295  0.281966  0.656324  0.997063  0.381397
 4  0.156479  0.821530  0.626344  0.839786  0.458741  0.433045  0.516273
 5  0.915996  0.836004  0.620669  0.040929  0.109346  0.764341  0.102826

           7         8         9
 0  0.207438  0.986314  0.303960
 1  0.688634  0.173580  0.306325
 2  0.806305  0.603795  0.743426
 3  0.151624  0.246504  0.996858
 4  0.297052  0.777210  0.486666
 5  0.108603  0.382444  0.385082  ,
           0         1         2         3         4         5         6  \
 0  0.177782  0.874031  0.616180  0.349608  0.634183  0.230146  0.792084
 1  0.664268  0.496821  0.828340  0.740635  0.032974  0.628262  0.483731
 2  0.606387  0.944795  0.098599  0.792360  0.141039  0.317621  0.829654
 3  0.230397  0.373564  0.135212  0.915823  0.509725  0.207517  0.882952
 4  0.463928  0.138554  0.416133  0.748138  0.497389  0.727022  0.282238
 5  0.693347  0.239969  0.225174  0.473345  0.836982  0.348598  0.143519

           7         8         9
 0  0.216698  0.919593  0.130465
 1  0.439311  0.989561  0.210769
 2  0.536419  0.621505  0.768228
 3  0.853802  0.867899  0.754628
 4  0.409798  0.785525  0.735761
 5  0.748597  0.995509  0.798851  ,
           0         1         2         3         4         5         6  \
 0  0.540415  0.186663  0.644489  0.764042  0.970164  0.444089  0.554272
 1  0.869363  0.113020  0.715786  0.100288  0.577663  0.546188  0.889218
 2  0.821364  0.736945  0.834156  0.646602  0.202923  0.624464  0.582237
 3  0.116033  0.191893  0.463933  0.180905  0.523882  0.764289  0.793972
 4  0.885100  0.057355  0.069332  0.643415  0.663839  0.991002  0.009379
 5  0.292221  0.258890  0.853131  0.430085  0.110998  0.689001  0.024218

           7         8         9
 0  0.258630  0.210916  0.388480
 1  0.644416  0.286280  0.993836
 2  0.577006  0.042120  0.546113
 3  0.738988  0.876767  0.591003
 4  0.181220  0.527930  0.192561
 5  0.085219  0.304259  0.971202  ,
           0         1         2         3         4         5         6  \
 0  0.214607  0.920633  0.568016  0.477087  0.741373  0.776520  0.231023
 1  0.739141  0.120426  0.393117  0.109635  0.699138  0.384898  0.400712
 2  0.385552  0.958517  0.511099  0.544317  0.397273  0.454750  0.113161
 3  0.250613  0.867910  0.222415  0.834837  0.259422  0.720406  0.120394
 4  0.594335  0.769740  0.862300  0.803353  0.282333  0.358383  0.252307
 5  0.034868  0.849666  0.755771  0.245101  0.229801  0.052056  0.489184

           7         8         9
 0  0.710402  0.685548  0.456295
 1  0.519986  0.738466  0.062962
 2  0.496770  0.868333  0.453895
 3  0.050607  0.297993  0.471470
 4  0.392748  0.323157  0.791894
 5  0.899774  0.990438  0.842098  ,
           0         1         2         3         4         5         6  \
 0  0.984384  0.072725  0.731522  0.779200  0.239223  0.735423  0.217619
 1  0.987877  0.631415  0.898173  0.231802  0.715826  0.790076  0.361228
 2  0.031649  0.218305  0.764939  0.517431  0.253039  0.431472  0.419584
 3  0.602874  0.885545  0.745619  0.470814  0.437400  0.750744  0.608260
 4  0.527720  0.446541  0.273960  0.748121  0.746237  0.198927  0.673974
 5  0.661320  0.253024  0.309364  0.754525  0.104162  0.783250  0.711071

           7         8         9
 0  0.182372  0.312907  0.192971
 1  0.444723  0.644224  0.441941
 2  0.385318  0.821762  0.013468
 3  0.538943  0.004167  0.453471
 4  0.678072  0.633705  0.491240
 5  0.345791  0.782394  0.572777  ]

## Q2.2

Make sure that the variable `file_list` contains the CSV files in the data directory (and only the CSV files)

In [ ]:
#TRUST ME LIL BRO

## Q2.2
Here you want to create a variable storing all the data in the CSV files in your data directory

To achieve this you can use the `read_csv()` method in the pandas library inside a list comprehension where you iterate over `file_list`

Store the data in a variable named `data_sets`

In [20]:
#done it but ill change name for ya 
data_sets = all_files_list

## Q2.3
Concatenate all the data store in `data_sets` into a dataframe using `the concat()` method from the pandas library

Store your dataframe in a variable named `df`

In [32]:
df = pd.concat(data_sets)
df = pd.DataFrame.reindex(df)

## Q2.4
Examine the dataframes first 40 rows by using the pandas `head()` method

In [33]:
df.head(40)

,0,1,2,3,4,5,6,7,8,9
0,0.972077,0.646035,0.533126,0.943473,0.023868,0.955283,0.165667,0.715487,0.269452,0.736947
1,0.819736,0.758109,0.794889,0.309026,0.580838,0.674574,0.431448,0.349162,0.109140,0.987664
2,0.075542,0.893006,0.705055,0.881107,0.127228,0.396477,0.986381,0.897388,0.762901,0.210352
3,0.170463,0.480887,0.258983,0.072511,0.816111,0.474031,0.745129,0.148653,0.890304,0.520209
4,0.415139,0.889190,0.263780,0.258482,0.554022,0.388369,0.007417,0.194194,0.576059,0.956678
5,0.147106,0.074295,0.045481,0.834139,0.600065,0.095220,0.802513,0.950219,0.933484,0.106030
0,0.264027,0.964930,0.166019,0.979061,0.923937,0.623234,0.834406,0.930507,0.839160,0.522875
1,0.258320,0.637756,0.317591,0.192193,0.220216,0.449298,0.121003,0.853171,0.658405,0.582496
2,0.340470,0.946588,0.604095,0.913370,0.193863,0.435900,0.636458,0.579789,0.644397,0.779777
3,0.568930,0.009381,0.598609,0.223873,0.303780,0.349022,0.348644,0.259113,0.219026,0.524392
4,0.325928,0.580347,0.808592,0.616384,0.602156,0.102621,0.390492,0.606321,0.022965,0.624083
5,0.943521,0.206190,0.051978,0.852592,0.160536,0.573881,0.142216,0.584250,0.364259,0.248642
0,0.707485,0.789624,0.425679,0.117072,0.154292,0.181508,0.156848,0.647157,0.236120,0.873562
1,0.009849,0.230776,0.833235,0.570922,0.195540,0.810397,0.951304,0.642084,0.860988,0.485705
2,0.437908,0.445475,0.387031,0.723512,0.542042,0.824992,0.902477,0.137933,0.336383,0.546531
3,0.355867,0.021528,0.197228,0.015251,0.688148,0.247983,0.371156,0.511989,0.697104,0.717978
4,0.699331,0.558848,0.874878,0.565221,0.227320,0.523653,0.386730,0.920449,0.209092,0.210046
5,0.446181,0.897401,0.307030,0.375517,0.132631,0.662397,0.999179,0.593294,0.968715,0.955091
0,0.740576,0.703888,0.635960,0.201376,0.333506,0.921203,0.240422,0.507092,0.710404,0.496614
1,0.955814,0.180323,0.922775,0.061503,0.252939,0.494738,0.737009,0.582887,0.214657,0.570323
2,0.139840,0.478558,0.349587,0.173535,0.605319,0.149547,0.224081,0.017461,0.256106,0.031711
3,0.223433,0.358509,0.617079,0.882206,0.243871,0.422363,0.337593,0.758400,0.729243,0.014322
4,0.529934,0.720701,0.613672,0.475738,0.838735,0.667907,0.039340,0.806723,0.803851,0.457624
5,0.551652,0.778406,0.115201,0.253204,0.241417,0.638059,0.631762,0.059920,0.122759,0.981465
0,0.385390,0.749017,0.251410,0.006835,0.317852,0.595623,0.386616,0.264623,0.164532,0.850798
1,0.113076,0.622563,0.550221,0.105007,0.410163,0.050102,0.975362,0.123897,0.096226,0.267682
2,0.440056,0.730651,0.367334,0.097116,0.833843,0.124944,0.500654,0.486800,0.875116,0.710462
3,0.629227,0.641817,0.863553,0.015075,0.907014,0.988228,0.241888,0.633092,0.487083,0.847807
4,0.574716,0.024898,0.120578,0.856961,0.201969,0.002041,0.867184,0.539172,0.890132,0.757211
5,0.596758,0.205773,0.312754,0.344289,0.916072,0.462229,0.870788,0.433023,0.963572,0.951630
0,0.584671,0.554514,0.803746,0.080318,0.195672,0.571731,0.434800,0.207438,0.986314,0.303960
1,0.163314,0.540963,0.747248,0.412400,0.392086,0.895591,0.302680,0.688634,0.173580,0.306325
2,0.897660,0.608840,0.981982,0.983594,0.768925,0.170911,0.189931,0.806305,0.603795,0.743426
3,0.509013,0.782233,0.111295,0.281966,0.656324,0.997063,0.381397,0.151624,0.246504,0.996858
4,0.156479,0.821530,0.626344,0.839786,0.458741,0.433045,0.516273,0.297052,0.777210,0.486666
5,0.915996,0.836004,0.620669,0.040929,0.109346,0.764341,0.102826,0.108603,0.382444,0.385082
0,0.177782,0.874031,0.616180,0.349608,0.634183,0.230146,0.792084,0.216698,0.919593,0.130465
1,0.664268,0.496821,0.828340,0.740635,0.032974,0.628262,0.483731,0.439311,0.989561,0.210769
2,0.606387,0.944795,0.098599,0.792360,0.141039,0.317621,0.829654,0.536419,0.621505,0.768228
3,0.230397,0.373564,0.135212,0.915823,0.509725,0.207517,0.882952,0.853802,0.867899,0.754628

## Q2.5
There seems to be a problem with indexing... 

Why do you think that is? 

Solve this problem by resetting the index!

In [35]:
df = df.reset_index()
df

,index,0,1,2,3,4,5,6,7,8,9
0,0,0.972077,0.646035,0.533126,0.943473,0.023868,0.955283,0.165667,0.715487,0.269452,0.736947
1,1,0.819736,0.758109,0.794889,0.309026,0.580838,0.674574,0.431448,0.349162,0.109140,0.987664
2,2,0.075542,0.893006,0.705055,0.881107,0.127228,0.396477,0.986381,0.897388,0.762901,0.210352
3,3,0.170463,0.480887,0.258983,0.072511,0.816111,0.474031,0.745129,0.148653,0.890304,0.520209
4,4,0.415139,0.889190,0.263780,0.258482,0.554022,0.388369,0.007417,0.194194,0.576059,0.956678
5,5,0.147106,0.074295,0.045481,0.834139,0.600065,0.095220,0.802513,0.950219,0.933484,0.106030
6,0,0.264027,0.964930,0.166019,0.979061,0.923937,0.623234,0.834406,0.930507,0.839160,0.522875
7,1,0.258320,0.637756,0.317591,0.192193,0.220216,0.449298,0.121003,0.853171,0.658405,0.582496
8,2,0.340470,0.946588,0.604095,0.913370,0.193863,0.435900,0.636458,0.579789,0.644397,0.779777
9,3,0.568930,0.009381,0.598609,0.223873,0.303780,0.349022,0.348644,0.259113,0.219026,0.524392
10,4,0.325928,0.580347,0.808592,0.616384,0.602156,0.102621,0.390492,0.606321,0.022965,0.624083
11,5,0.943521,0.206190,0.051978,0.852592,0.160536,0.573881,0.142216,0.584250,0.364259,0.248642
12,0,0.707485,0.789624,0.425679,0.117072,0.154292,0.181508,0.156848,0.647157,0.236120,0.873562
13,1,0.009849,0.230776,0.833235,0.570922,0.195540,0.810397,0.951304,0.642084,0.860988,0.485705
14,2,0.437908,0.445475,0.387031,0.723512,0.542042,0.824992,0.902477,0.137933,0.336383,0.546531
15,3,0.355867,0.021528,0.197228,0.015251,0.688148,0.247983,0.371156,0.511989,0.697104,0.717978
16,4,0.699331,0.558848,0.874878,0.565221,0.227320,0.523653,0.386730,0.920449,0.209092,0.210046
17,5,0.446181,0.897401,0.307030,0.375517,0.132631,0.662397,0.999179,0.593294,0.968715,0.955091
18,0,0.740576,0.703888,0.635960,0.201376,0.333506,0.921203,0.240422,0.507092,0.710404,0.496614
19,1,0.955814,0.180323,0.922775,0.061503,0.252939,0.494738,0.737009,0.582887,0.214657,0.570323
20,2,0.139840,0.478558,0.349587,0.173535,0.605319,0.149547,0.224081,0.017461,0.256106,0.031711
21,3,0.223433,0.358509,0.617079,0.882206,0.243871,0.422363,0.337593,0.758400,0.729243,0.014322
22,4,0.529934,0.720701,0.613672,0.475738,0.838735,0.667907,0.039340,0.806723,0.803851,0.457624
23,5,0.551652,0.778406,0.115201,0.253204,0.241417,0.638059,0.631762,0.059920,0.122759,0.981465
24,0,0.385390,0.749017,0.251410,0.006835,0.317852,0.595623,0.386616,0.264623,0.164532,0.850798
25,1,0.113076,0.622563,0.550221,0.105007,0.410163,0.050102,0.975362,0.123897,0.096226,0.267682
26,2,0.440056,0.730651,0.367334,0.097116,0.833843,0.124944,0.500654,0.486800,0.875116,0.710462
27,3,0.629227,0.641817,0.863553,0.015075,0.907014,0.988228,0.241888,0.633092,0.487083,0.847807
28,4,0.574716,0.024898,0.120578,0.856961,0.201969,0.002041,0.867184,0.539172,0.890132,0.757211
29,5,0.596758,0.205773,0.312754,0.344289,0.916072,0.462229,0.870788,0.433023,0.963572,0.951630
30,0,0.584671,0.554514,0.803746,0.080318,0.195672,0.571731,0.434800,0.207438,0.986314,0.303960
31,1,0.163314,0.540963,0.747248,0.412400,0.392086,0.895591,0.302680,0.688634,0.173580,0.306325
32,2,0.897660,0.608840,0.981982,0.983594,0.768925,0.170911,0.189931,0.806305,0.603795,0.743426
33,3,0.509013,0.782233,0.111295,0.281966,0.656324,0.997063,0.381397,0.151624,0.246504,0.996858
34,4,0.156479,0.821530,0.626344,0.839786,0.458741,0.433045,0.516273,0.297052,0.777210,0.486666
35,5,0.915996,0.836004,0.620669,0.040929,0.109346,0.764341,0.102826,0.108603,0.382444,0.385082
36,0,0.177782,0.874031,0.616180,0.349608,0.634183,0.230146,0.792084,0.216698,0.919593,0.130465
37,1,0.664268,0.496821,0.828340,0.740635,0.032974,0.628262,0.483731,0.439311,0.989561,0.210769
38,2,0.606387,0.944795,0.098599,0.792360,0.141039,0.317621,0.829654,0.536419,0.621505,0.768228
39,3,0.230397,0.373564,0.135212,0.915823,0.509725,0.207517,0.882952,0.853802,0.867899,0.754628
40,4,0.463928,0.138554,0.416133,0.748138,0.497389,0.727022,0.282238,0.409798,0.785525,0.735761
41,5,0.693347,0.239969,0.225174,0.473345,0.836982,0.348598,0.143519,0.748597,0.995509,0.798851
42,0,0.540415,0.186663,0.644489,0.764042,0.970164,0.444089,0.554272,0.258630,0.210916,0.388480
43,1,0.869363,0.113020,0.715786,0.100288,0.577663,0.546188,0.889218,0.644416,0.286280,0.993836
44,2,0.821364,0.736945,0.834156,0.646602,0.202923,0.624464,0.582237,0.577006,0.042120,0.546113
45,3,0.116033,0.191893,0.463933,0.180905,0.523882,0.764289,0.793972,0.738988,0.876767,0.591003
46,4,0.885100,0.057355,0.069332,0.643415,0.663839,0.991002,0.009379,0.181220,0.527930,0.192561
47,5,0.292221,0.258890,0.853131,0.430085,0.110998,0.689001,0.024218,0.085219,0.304259,0.971202
48,0,0.214607,0.920633,0.568016,0.477087,0.741373,0.776520,0.231023,0.710402,0.685548,0.456295
49,1,0.739141,0.120426,0.393117,0.109635,0.699138,0.384898,0.400712,0.519986,0.738466,0.062962
50,2,0.385552,0.958517,0.511099,0.544317,0.397273,0.454750,0.113161,0.496770,0.868333,0.453895
51,3,0.250613,0.867910,0.222415,0.834837,0.259422,0.720406,0.120394,0.050607,0.297993,0.471470
52,4,0.594335,0.769740,0.862300,0.803353,0.282333,0.358383,0.252307,0.392748,0.323157,0.791894
53,5,0.034868,0.849666,0.755771,0.245101,0.229801,0.052056,0.489184,0.899774,0.990438,0.842098
54,0,0.984384,0.072725,0.731522,0.779200,0.239223,0.735423,0.217619,0.182372,0.312907,0.192971
55,1,0.987877,0.631415,0.898173,0.231802,0.715826,0.790076,0.361228,0.444723,0.644224,0.441941
56,2,0.031649,0.218305,0.764939,0.517431,0.253039,0.431472,0.419584,0.385318,0.821762,0.013468
57,3,0.602874,0.885545,0.745619,0.470814,0.437400,0.750744,0.608260,0.538943,0.004167,0.453471
58,4,0.527720,0.446541,0.273960,0.748121,0.746237,0.198927,0.673974,0.678072,0.633705,0.491240
59,5,0.661320,0.253024,0.309364,0.754525,0.104162,0.783250,0.711071,0.345791,0.782394,0.572777

# WELL DONE!
___

# BONUS CHALLENGE

Create a list comprehension that calculates the median of every column in `df` that has a median higher than 0.56

In [43]:
list_high_median = [(i, f"Median: {float(df[i].median())}") for i in df.columns if df[i].median() > 0.56 and i != "index"  ]
list_high_median

[('1', 'Median: 0.5945934470669112'), ('8', 'Median: 0.6389640351523087')]

In [39]:
df["2"].median()

np.float64(0.5591184629102928)